spring.application.name=com.watchify.app

# =================================================
# SERVER
# =================================================
server.port=8080

# =================================================
# DATABASE - POSTGRESQL
# =================================================
spring.datasource.url=jdbc:postgresql://ep-still-sky-a4sqlbza-pooler.us-east-1.aws.neon.tech:5432/webflix_db?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_4uOFhonUixN6
spring.datasource.driver-class-name=org.postgresql.Driver

# =================================================
# JPA / HIBERNATE
# =================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


jwt.secret=WatchifySuperSecretKey_AtLeast_32_Characters_Long


spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# =================================================
# CONNECTION POOL (HIKARI)
# =================================================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000

# =================================================
# FILE UPLOAD (VIDEO / IMAGE)
# =================================================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB

server.tomcat.max-swallow-size=-1
server.tomcat.max-http-form-post-size=-1

file.upload.video-dir=uploads/videos
file.upload.image-dir=uploads/images

# =================================================
# MAIL (GMAIL SMTP)
# =================================================

app.frontend.url=https://web-flix-frontend.vercel.app
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=officialpankaj169@gmail.com
spring.mail.password=vnaxnoxgyqsnhchn

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# =================================================
# LOGGING (OPTIONAL)
# =================================================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.web.servlet.handler.HandlerMappingIntrospector=ERROR

